name: Terraform Checks and Plan

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-plan.yml'
  push:
    branches:
      - sprint-04-cicd
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-plan.yml'

permissions:
  id-token: write
  contents: read

jobs:
  terraform-pr-checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    env:
      TF_VAR_account_a_api_id: ${{ vars.TF_VAR_account_a_api_id }}
      TF_VAR_account_b_data_id: ${{ vars.TF_VAR_account_b_data_id }}
      TF_VAR_aws_region: ${{ vars.TF_VAR_aws_region }}
      TF_VAR_alert_email: ${{ vars.TF_VAR_alert_email}}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (without backend)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  terraform-plan:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    env:
      TF_VAR_account_a_api_id: ${{ vars.TF_VAR_account_a_api_id }}
      TF_VAR_account_b_data_id: ${{ vars.TF_VAR_account_b_data_id }}
      TF_VAR_aws_region: ${{ vars.TF_VAR_aws_region }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -input=false